Models/Pilot.cs
using System.ComponentModel.DataAnnotations;

namespace AirportApplication.Models
{
    public class Pilot
    {
        public int Id { get; set; }

        [Display(Name = "First Name")]
        [StringLength(60, MinimumLength = 3)]
        [Required]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [StringLength(60, MinimumLength = 3)]
        [Required]
        public string LastName { get; set; }

        [StringLength(60, MinimumLength = 3)]
        [Required]
        public string Rank { get; set; }

        [Display(Name = "Date of birth")]
        [Required]
        [DataType(DataType.Date)]
        public DateTime DateOfBirth { get; set; }

        [StringLength(40)]
        public string? Nationality { get; set; }

        [Display(Name = "Profile Picutre")]
        public string? ProfilePicture { get; set; }

        [Display(Name = "Company")]
        public int? CompanyId { get; set; }
        public Company? Company { get; set; }
        
        public string FullName
        {
            get
            {
                return string.Format("{0} {1}", FirstName, LastName);
            }
        }
    }
}

Controllers/PilotsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AirportApplication.Data;
using AirportApplication.Models;
using AirportApplication.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace AirportApplication.Controllers
{
    public class PilotsController : Controller
    {
        private readonly AirportApplicationContext _context;

        public PilotsController(AirportApplicationContext context)
        {
            _context = context;
        }

        // GET: Pilots
        public async Task<IActionResult> Index(string FullName, string Rank, string Company)
        {
            IQueryable<Pilot> pilotsQuery = _context.Pilot.AsQueryable().Include(x => x.Company);
            IQueryable<string> ranksQuery = _context.Pilot.OrderBy(x => x.Rank).Select(x => x.Rank).Distinct();
            IQueryable<string> companyQuery = _context.Pilot.OrderBy(x => x.Company.Title).Select(x => x.Company.Title).Distinct();

            if (!string.IsNullOrEmpty(FullName))
            {
                if (FullName.Contains(" "))
                {
                    string[] names = FullName.Split(" ");
                    pilotsQuery = pilotsQuery.Where(x => x.FirstName.Contains(names[0]) || x.LastName.Contains(names[1]) ||
                    x.FirstName.Contains(names[1]) || x.LastName.Contains(names[0]));
                }
                else
                {
                    pilotsQuery = pilotsQuery.Where(x => x.FirstName.Contains(FullName) || x.LastName.Contains(FullName));
                }
            }
            if (!string.IsNullOrEmpty(Rank))
            {
                pilotsQuery = pilotsQuery.Where(x => x.Rank.Contains(Rank));
            }
            if (!string.IsNullOrEmpty(Company))
            {
                pilotsQuery = pilotsQuery.Where(x => x.Company.Title.Contains(Company));
            }

            var PilotFilterVM = new PilotFilter
            {
                Pilots = await pilotsQuery.Include(x => x.Company).ToListAsync(),
                Ranks = new SelectList(await ranksQuery.ToListAsync()),
                Companies = new SelectList(await companyQuery.ToListAsync())
            };

            return View(PilotFilterVM);
        }

        // GET: Pilots/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pilot == null)
            {
                return NotFound();
            }

            var pilot = await _context.Pilot
                .Include(p => p.Company)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pilot == null)
            {
                return NotFound();
            }

            return View(pilot);
        }

        // GET: Pilots/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["CompanyId"] = new SelectList(_context.Company, "Id", "Title");
            return View();
        }

        // POST: Pilots/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(AddOrEditPilot viewmodel)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;
                if (viewmodel.ProfilePictureFile != null)
                {
                    uniqueFileName = UploadedFile(viewmodel);
                }
                Pilot pilot = new Pilot
                {
                    FirstName = viewmodel.Pilot.FirstName,
                    LastName = viewmodel.Pilot.LastName,
                    Rank = viewmodel.Pilot.Rank,
                    DateOfBirth = viewmodel.Pilot.DateOfBirth,
                    Nationality = viewmodel.Pilot.Nationality,
                    ProfilePicture = uniqueFileName,
                    CompanyId = viewmodel.Pilot.CompanyId
                };
                _context.Add(pilot);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanyId"] = new SelectList(_context.Company, "Id", "Title", viewmodel.Pilot.CompanyId);
            return View(viewmodel);
        }

        // GET: Pilots/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pilot == null)
            {
                return NotFound();
            }

            var pilot = await _context.Pilot.FindAsync(id);
            if (pilot == null)
            {
                return NotFound();
            }

            AddOrEditPilot viewmodel = new AddOrEditPilot
            {
                Pilot = pilot,
                ProfilePictureName = pilot.ProfilePicture
            };

            ViewData["CompanyId"] = new SelectList(_context.Company, "Id", "Title", pilot.CompanyId);
            return View(viewmodel);
        }

        // POST: Pilots/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, AddOrEditPilot viewmodel)
        {
            if (id != viewmodel.Pilot.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (viewmodel.ProfilePictureFile != null)
                    {
                        string uniqueFileName = UploadedFile(viewmodel);
                        viewmodel.Pilot.ProfilePicture = uniqueFileName;
                    }
                    else
                    {
                        viewmodel.Pilot.ProfilePicture = viewmodel.ProfilePictureName;
                    }
                    _context.Update(viewmodel.Pilot);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PilotExists(viewmodel.Pilot.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanyId"] = new SelectList(_context.Company, "Id", "Title", viewmodel.Pilot.CompanyId);
            return View(viewmodel);
        }

        private string UploadedFile(AddOrEditPilot viewmodel)
        {
            string uniqueFileName = null;

            if (viewmodel.ProfilePictureFile != null)
            {
                string uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/profilePictures");
                if (!Directory.Exists(uploadsFolder))
                {
                    Directory.CreateDirectory(uploadsFolder);
                }
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(viewmodel.ProfilePictureFile.FileName);
                string fileNameWithPath = Path.Combine(uploadsFolder, uniqueFileName);

                using (var stream = new FileStream(fileNameWithPath, FileMode.Create))
                {
                    viewmodel.ProfilePictureFile.CopyTo(stream);
                }
            }
            return uniqueFileName;
        }

        // GET: Pilots/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Pilot == null)
            {
                return NotFound();
            }

            var pilot = await _context.Pilot
                .Include(p => p.Company)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pilot == null)
            {
                return NotFound();
            }

            return View(pilot);
        }

        // POST: Pilots/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Pilot == null)
            {
                return Problem("Entity set 'AirportApplicationContext.Pilot'  is null.");
            }
            var pilot = await _context.Pilot.FindAsync(id);
            if (pilot != null)
            {
                _context.Pilot.Remove(pilot);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PilotExists(int id)
        {
          return (_context.Pilot?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        // GET: PilotsByCompany
        public async Task<IActionResult> PilotsByCompany(int? Id, string FullName, string Rank, string Company)
        {
            IQueryable<Pilot> pilotsQuery = _context.Pilot.Where(x => x.CompanyId == Id).Include(x => x.Company);
            IQueryable<string> ranksQuery = _context.Pilot.OrderBy(x => x.Rank).Select(x => x.Rank).Distinct();
            IQueryable<string> companyQuery = _context.Pilot.OrderBy(x => x.Company.Title).Select(x => x.Company.Title).Distinct();

            var company = await _context.Company.FirstOrDefaultAsync(m => m.Id == Id);
            ViewBag.Message = company.Title;

            if (!string.IsNullOrEmpty(FullName))
            {
                if (FullName.Contains(" "))

Views/Pilots/Create.cshtml
@model AirportApplication.ViewModels.AddOrEditPilot

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Pilot</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Pilot.FirstName" class="control-label"></label>
                <input asp-for="Pilot.FirstName" class="form-control" />
                <span asp-validation-for="Pilot.FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pilot.LastName" class="control-label"></label>
                <input asp-for="Pilot.LastName" class="form-control" />
                <span asp-validation-for="Pilot.LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pilot.Rank" class="control-label"></label>
                <input asp-for="Pilot.Rank" class="form-control" />
                <span asp-validation-for="Pilot.Rank" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pilot.DateOfBirth" class="control-label"></label>
                <input asp-for="Pilot.DateOfBirth" class="form-control" />
                <span asp-validation-for="Pilot.DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pilot.Nationality" class="control-label"></label>
                <input asp-for="Pilot.Nationality" class="form-control" />
                <span asp-validation-for="Pilot.Nationality" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none">
                <label asp-for="Pilot.ProfilePicture" class="control-label"></label>
                <input asp-for="Pilot.ProfilePicture" class="form-control" readonly="@(true)"/>
                <span asp-validation-for="Pilot.ProfilePicture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pilot.CompanyId" class="control-label"></label>
                <select asp-for="Pilot.CompanyId" class ="form-control" asp-items="ViewBag.CompanyId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProfilePictureFile" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="ProfilePictureFile" class="custom-file-input" id="customFile">
                    <label class="custom-file-label" for="customFile"></label>
                    <span asp-validation-for="ProfilePictureFile" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Pilots/Delete.cshtml
@model AirportApplication.Models.Pilot

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this pilot?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rank)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rank)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nationality)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nationality)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfilePicture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProfilePicture)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Company.Country)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Pilots/Details.cshtml
@model AirportApplication.Models.Pilot

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Pilot</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rank)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rank)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nationality)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nationality)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Company.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfilePicture)
        </dt>
        <dd class = "col-sm-10">
            <img src="~/profilePictures/@Model.ProfilePicture"
            width=20% height=100% position=absolute
            asp-append-version="true" />
        </dd>
    </dl>
</div>
<div>
    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
    {
        <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> 
        @Html.Raw("|");
    }
    <a href="javascript:void(0);" onclick="history.go(-1);">Back to List</a>
</div>

Views/Pilots/Edit.cshtml
@model AirportApplication.ViewModels.AddOrEditPilot

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Pilot</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Pilot.Id" />
            <div class="form-group">
                <label asp-for="Pilot.FirstName" class="control-label"></label>
                <input asp-for="Pilot.FirstName" class="form-control" />
                <span asp-validation-for="Pilot.FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pilot.LastName" class="control-label"></label>
                <input asp-for="Pilot.LastName" class="form-control" />
                <span asp-validation-for="Pilot.LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pilot.Rank" class="control-label"></label>
                <input asp-for="Pilot.Rank" class="form-control" />
                <span asp-validation-for="Pilot.Rank" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pilot.DateOfBirth" class="control-label"></label>
                <input asp-for="Pilot.DateOfBirth" class="form-control" />
                <span asp-validation-for="Pilot.DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pilot.Nationality" class="control-label"></label>
                <input asp-for="Pilot.Nationality" class="form-control" />
                <span asp-validation-for="Pilot.Nationality" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none">
                <label asp-for="Pilot.ProfilePicture" class="control-label"></label>
                <input asp-for="ProfilePictureName" class="form-control" readonly="@(true)"/>
                <span asp-validation-for="Pilot.ProfilePicture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProfilePictureFile" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="ProfilePictureFile" class="custom-file-input" id="customFile">
                    <label class="custom-file-label" for="customFile"></label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Pilot.CompanyId" class="control-label"></label>
                <select asp-for="Pilot.CompanyId" class="form-control" asp-items="ViewBag.CompanyId"></select>
                <span asp-validation-for="Pilot.CompanyId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Pilots/Index.cshtml
@model AirportApplication.ViewModels.PilotFilter

@{
    ViewData["Title"] = "Index";
}

<h1>Pilots</h1>

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}

<form asp-controller="Pilots" asp-action="Index" method="get">
    <p>
        First or last name: <input type="text" asp-for="FullName" />
        Rank:
        <select asp-for="Rank" asp-items="Model.Ranks">
            <option value="">All</option>
        </select>
        Company:
        <select asp-for="Company" asp-items="Model.Companies">
            <option value="">All</option>
        </select>
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Pilots[0].FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pilots[0].FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pilots[0].LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pilots[0].Rank)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pilots[0].DateOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pilots[0].Nationality)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pilots[0].Company)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Pilots) {
        <tr>
            <td width=20%>
                <img src="~/profilePictures/@item.ProfilePicture"
                width=100% height=100% position=absolute/>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rank)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nationality)
            </td>
            <td>
                <a asp-controller="Companies" asp-action="Details" asp-route-id="@item.CompanyId">@Html.DisplayFor(modelItem => item.Company.Title)</a>    
            </td>
            <td>
                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    @Html.Raw("|");
                }
                <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    @Html.Raw("|");
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                }
            </td>
        </tr>
}
    </tbody>
</table>

Views/Pilots/PilotsByCompany.cshtml
@model AirportApplication.ViewModels.PilotFilter

@{
    ViewData["Title"] = "Index";
}

<h1>Pilots working at "@ViewBag.Message"</h1>

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}

<form asp-controller="Pilots" asp-action="PilotsByCompany" method="get">
    <p>
        First or last name: <input type="text" asp-for="FullName" />
        Rank:
        <select asp-for="Rank" asp-items="Model.Ranks">
            <option value="">All</option>
        </select>
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Pilots[0].FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pilots[0].FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pilots[0].LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pilots[0].Rank)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pilots[0].DateOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pilots[0].Nationality)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pilots[0].Company)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Pilots) {
        <tr>
            <td width=20%>
                <img src="~/profilePictures/@item.ProfilePicture"
                width=100% height=100% position=absolute/>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rank)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nationality)
            </td>
            <td>
                <a asp-controller="Companies" asp-action="Details" asp-route-id="@item.CompanyId">@Html.DisplayFor(modelItem => item.Company.Title)</a>    
            </td>
            <td>
                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    @Html.Raw("|");
                }
                <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    @Html.Raw("|");
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                }
            </td>
        </tr>
}
    </tbody>
</table>