Models/Flight.cs
using System.ComponentModel.DataAnnotations;

namespace AirportApplication.Models
{
    public class Flight
    { 
        public int Id { get; set; }

        [StringLength(100, MinimumLength = 3)]
        [Required]
        public string Origin { get; set; }

        [StringLength(100, MinimumLength = 3)]
        [Required]
        public string Destination { get; set; }

        public ICollection<CompanyFlight>? CompanyFlights { get; set; }

        [Display(Name = "Origin-Destination")]
        public string FlightName
        {
            get
            {
                return string.Format("{0}-{1}", Origin, Destination);
            }
        }
    }
}

Controllers/CompanyFlightsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AirportApplication.Data;
using AirportApplication.Models;
using AirportApplication.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace AirportApplication.Controllers
{
    public class CompanyFlightsController : Controller
    {
        private readonly AirportApplicationContext _context;

        public CompanyFlightsController(AirportApplicationContext context)
        {
            _context = context;
        }

        // GET: CompanyFlights
        public async Task<IActionResult> Index(string Title, string Origin, string Destination, string Sort)
        {
            IQueryable<CompanyFlight> companyFlightQuery = _context.CompanyFlight.AsQueryable().Include(x => x.Flight).Include(x => x.Companies);
            IQueryable<string> originQuery = _context.CompanyFlight.OrderBy(x => x.Flight.Origin).Select(x => x.Flight.Origin).Distinct();
            IQueryable<string> destinationQuery = _context.CompanyFlight.OrderBy(x => x.Flight.Destination).Select(x => x.Flight.Destination).Distinct();
            List<string> sortTypesList = new List<string>(2);
            sortTypesList.Add("Ascending");
            sortTypesList.Add("Descending");
            

            if (!string.IsNullOrEmpty(Title))
            {
                companyFlightQuery = companyFlightQuery.Where(x => x.Companies.Title.Contains(Title));
            }
            if (!string.IsNullOrEmpty(Origin))
            {
                companyFlightQuery = companyFlightQuery.Where(x => x.Flight.Origin.Contains(Origin));
            }
            if (!string.IsNullOrEmpty(Destination))
            {
                companyFlightQuery = companyFlightQuery.Where(x => x.Flight.Destination.Contains(Destination));
            }
            if (!string.IsNullOrEmpty(Sort))
            {
                if (string.Compare(Sort, "Ascending") == 0)
                {
                    companyFlightQuery = companyFlightQuery.OrderBy(x => x.Price);
                }
                else
                {
                    companyFlightQuery = companyFlightQuery.OrderByDescending(x => x.Price);
                }
            }

            var CompanyFlightFilterVM = new CompanyFlightFilter
            {
                CompanyFlights = await companyFlightQuery.ToListAsync(),
                Origins = new SelectList(await originQuery.ToListAsync()),
                Destinations = new SelectList(await destinationQuery.ToListAsync()),
                SortTypes = new SelectList (sortTypesList)
            };

            return View(CompanyFlightFilterVM);
        }

        // GET: CompanyFlights/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null || _context.CompanyFlight == null)
            {
                return NotFound();
            }

            var companyFlight = await _context.CompanyFlight
                .Include(c => c.Companies)
                .Include(c => c.Flight)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (companyFlight == null)
            {
                return NotFound();
            }

            return View(companyFlight);
        }

        // GET: CompanyFlights/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["CompanyId"] = new SelectList(_context.Company, "Id", "Title");
            ViewData["FlightId"] = new SelectList(_context.Flight, "Id", "FlightName");
            return View();
        }

        // POST: CompanyFlights/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,CompanyId,FlightId,Price,DateOfFlight,Duration")] CompanyFlight companyFlight)
        {
            if (ModelState.IsValid)
            {
                _context.Add(companyFlight);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanyId"] = new SelectList(_context.Company, "Id", "Title", companyFlight.CompanyId);
            ViewData["FlightId"] = new SelectList(_context.Flight, "Id", "FlightName", companyFlight.FlightId);
            return View(companyFlight);
        }

        // GET: CompanyFlights/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || _context.CompanyFlight == null)
            {
                return NotFound();
            }

            var companyFlight = await _context.CompanyFlight.FindAsync(id);
            if (companyFlight == null)
            {
                return NotFound();
            }
            ViewData["CompanyId"] = new SelectList(_context.Company, "Id", "Title", companyFlight.CompanyId);
            ViewData["FlightId"] = new SelectList(_context.Flight, "Id", "FlightName", companyFlight.FlightId);
            return View(companyFlight);
        }

        // POST: CompanyFlights/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(long id, [Bind("Id,CompanyId,FlightId,Price,DateOfFlight,Duration")] CompanyFlight companyFlight)
        {
            if (id != companyFlight.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(companyFlight);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyFlightExists(companyFlight.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanyId"] = new SelectList(_context.Company, "Id", "Title", companyFlight.CompanyId);
            ViewData["FlightId"] = new SelectList(_context.Flight, "Id", "FlightName", companyFlight.FlightId);
            return View(companyFlight);
        }

        // GET: CompanyFlights/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || _context.CompanyFlight == null)
            {
                return NotFound();
            }

            var companyFlight = await _context.CompanyFlight
                .Include(c => c.Companies)
                .Include(c => c.Flight)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (companyFlight == null)
            {
                return NotFound();
            }

            return View(companyFlight);
        }

        // POST: CompanyFlights/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            if (_context.CompanyFlight == null)
            {
                return Problem("Entity set 'AirportApplicationContext.CompanyFlight'  is null.");
            }
            var companyFlight = await _context.CompanyFlight.FindAsync(id);
            if (companyFlight != null)
            {
                _context.CompanyFlight.Remove(companyFlight);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompanyFlightExists(long id)
        {
          return (_context.CompanyFlight?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        // GET: FlightsByCompany
        public async Task<IActionResult> FlightsByCompany(int? Id, string Title, string Origin, string Destination, string Sort)
        {
            IQueryable<CompanyFlight> companyFlightQuery = _context.CompanyFlight.Where(x => x.CompanyId == Id).Include(x => x.Flight).Include(x => x.Companies);
            IQueryable<string> originQuery = _context.CompanyFlight.OrderBy(x => x.Flight.Origin).Select(x => x.Flight.Origin).Distinct();
            IQueryable<string> destinationQuery = _context.CompanyFlight.OrderBy(x => x.Flight.Destination).Select(x => x.Flight.Destination).Distinct();
            List<string> sortTypesList = new List<string>(2);
            sortTypesList.Add("Ascending");
            sortTypesList.Add("Descending");

            var company = await _context.Company.FirstOrDefaultAsync(m => m.Id == Id);
            ViewBag.Message = company.Title;

            if (!string.IsNullOrEmpty(Title))
            {
                companyFlightQuery = companyFlightQuery.Where(x => x.Companies.Title.Contains(Title));
            }
            if (!string.IsNullOrEmpty(Origin))
            {
                companyFlightQuery = companyFlightQuery.Where(x => x.Flight.Origin.Contains(Origin));
            }
            if (!string.IsNullOrEmpty(Destination))
            {
                companyFlightQuery = companyFlightQuery.Where(x => x.Flight.Destination.Contains(Destination));
            }
            if (!string.IsNullOrEmpty(Sort))
            {
                if (string.Compare(Sort, "Ascending") == 0)
                {

Controllers/FlightsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AirportApplication.Data;
using AirportApplication.Models;
using AirportApplication.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace AirportApplication.Controllers
{
    public class FlightsController : Controller
    {
        private readonly AirportApplicationContext _context;

        public FlightsController(AirportApplicationContext context)
        {
            _context = context;
        }

        // GET: Flights
        public async Task<IActionResult> Index(string Origin, string Destination)
        {
            IQueryable<Flight> flightQuery = _context.Flight.AsQueryable();
            IQueryable<string> originQuery = _context.Flight.OrderBy(x => x.Origin).Select(x => x.Origin).Distinct();
            IQueryable<string> destinationQuery = _context.Flight.OrderBy(x => x.Destination).Select(x => x.Destination).Distinct();

            if (!string.IsNullOrEmpty(Origin))
            {
                flightQuery = flightQuery.Where(x => x.Origin.Contains(Origin));
            }
            if (!string.IsNullOrEmpty(Destination))
            {
                flightQuery = flightQuery.Where(x => x.Destination.Contains(Destination));
            }

            var FlightFilterVM = new FlightFilter
            {
                Flights = await flightQuery.ToListAsync(),
                Origins = new SelectList(await originQuery.ToListAsync()),
                Destinations = new SelectList(await destinationQuery.ToListAsync()),
            };

            return View(FlightFilterVM);
        }

        // GET: Flights/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Flight == null)
            {
                return NotFound();
            }

            var flight = await _context.Flight
                .FirstOrDefaultAsync(m => m.Id == id);
            if (flight == null)
            {
                return NotFound();
            }

            return View(flight);
        }

        // GET: Flights/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Flights/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Origin,Destination")] Flight flight)
        {
            if (ModelState.IsValid)
            {
                _context.Add(flight);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(flight);
        }

        // GET: Flights/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Flight == null)
            {
                return NotFound();
            }

            var flight = await _context.Flight.FindAsync(id);
            if (flight == null)
            {
                return NotFound();
            }
            return View(flight);
        }

        // POST: Flights/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Origin,Destination")] Flight flight)
        {
            if (id != flight.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(flight);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FlightExists(flight.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(flight);
        }

        // GET: Flights/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Flight == null)
            {
                return NotFound();
            }

            var flight = await _context.Flight
                .FirstOrDefaultAsync(m => m.Id == id);
            if (flight == null)
            {
                return NotFound();
            }

            return View(flight);
        }

        // POST: Flights/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Flight == null)
            {
                return Problem("Entity set 'AirportApplicationContext.Flight'  is null.");
            }
            var flight = await _context.Flight.FindAsync(id);
            if (flight != null)
            {
                _context.Flight.Remove(flight);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FlightExists(int id)
        {
          return (_context.Flight?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Flights/Create.cshtml
@model AirportApplication.Models.Flight

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Destination</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Origin" class="control-label"></label>
                <input asp-for="Origin" class="form-control" />
                <span asp-validation-for="Origin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Destination" class="control-label"></label>
                <input asp-for="Destination" class="form-control" />
                <span asp-validation-for="Destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Flights/Delete.cshtml
@model AirportApplication.Models.Flight

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this destination?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Origin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Origin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Destination)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Flights/Details.cshtml
@model AirportApplication.Models.Flight

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Destination</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Origin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Origin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Destination)
        </dd>
    </dl>
</div>
<div>
    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
    {
        <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> 
        @Html.Raw("|");
    }
    <a href="javascript:void(0);" onclick="history.go(-1);">Back to List</a>
</div>

Views/Flights/Edit.cshtml
@model AirportApplication.Models.Flight

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Destination</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Origin" class="control-label"></label>
                <input asp-for="Origin" class="form-control" />
                <span asp-validation-for="Origin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Destination" class="control-label"></label>
                <input asp-for="Destination" class="form-control" />
                <span asp-validation-for="Destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Flights/Index.cshtml
@model AirportApplication.ViewModels.FlightFilter

@{
    ViewData["Title"] = "Index";
}

<h1>Destinations</h1>

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}

<form asp-controller="Flights" asp-action="Index" method="get">
    <p>
        Origin:
        <select asp-for="Origin" asp-items="Model.Origins">
            <option value="">All</option>
        </select>
        Destination:
        <select asp-for="Destination" asp-items="Model.Destinations">
            <option value="">All</option>
        </select>
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Flights[0].Origin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Flights[0].Destination)
            </th>
            <th>
                View Flights
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Flights) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Origin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Destination)
            </td>
            <td>
               <a asp-controller="CompanyFlights" asp-action="FlightsByDestination" asp-route-id="@item.Id">View Flights</a>
            </td>
            <td>
                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    @Html.Raw("|");
                }
                <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    @Html.Raw("|");
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                }
            </td>
        </tr>
}
    </tbody>
</table>